
styles:
  - column_classes:
    - one-column
    - two-columns
  - list_classes:
    - list-style-1
  - table_border_classes:
    - no-borders
    - underline-first-row
    - grid-border
  - table_classes:
    - full-width
    - narrow-center
  - table_color_classes:
    - colorize-first-row
    - transparent-first-row
  - line_height_size:
    - from: 1.0
      to: 1.05
      step: 0.05
    - from: 1.5
      to: 1.55
      step: 0.05
  - paragraph_font_size:
    - from: 12
      to: 12
    - from: 14
      to: 14
  - image_max_width:
    - 50
    - 100